# Generated by Django 4.0.4 on 2022-05-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время посещения'),
        ),
    ]
